services:
  - type: web
    name: carbon-credit-api
    env: csharp
    rootDir: backend
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/CarbonCredit.AuthAPI.dll"
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        value: "Host=db.rardszalvrgfplwugpur.supabase.co; Port=5432; Database=postgres; Username=postgres; Password=345210472008Rm.; SslMode=Require; Trust Server Certificate=true"
      - key: JwtSettings__SecretKey
        value: "CarbonCredit2024SuperSecretKeyForJWTTokenGeneration123456789"