services:
  - type: web
    name: carbon-credit-api
    rootDir: backend
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/CarbonCredit.AuthAPI.dll"
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080